
CREATE TABLE [AUTOR] 
(
[ID] INT PRIMARY KEY  IDENTITY (1,1),
[FirstName] VARCHAR(50),
[LastName] VARCHAR (50)
)

CREATE TABLE [CATEGORY]
(
[ID] INT PRIMARY KEY IDENTITY (1,1),
[Name] VARCHAR(50)
)

CREATE TABLE [DOCUMENT] 
(
[DateCreated] DATE DEFAULT (GETDATE()),
[Name] VARCHAR(100),
[Owner] INT,
[CATEGORY] INT,
CONSTRAINT [NameUQ] UNIQUE ([Name]),
CONSTRAINT [PKDOCUMENT] PRIMARY KEY ([DateCreated],[Name]),
CONSTRAINT [AUTORFK] foreign KEY  ([Owner]) REFERENCES [AUTOR]([ID]),
CONSTRAINT [CATEGORYFK] foreign KEY  ([CATEGORY]) REFERENCES CATEGORY([ID]) 
)

//https://www.youtube.com/watch?v=CLVJVA9cTuU tworzenie bazy